export const darkTheme = {
  colors: {
    primary: "#6352bc",
    primaryLight: "#2B2466",
    primaryDark: "#E7E4FE",
    primaryHover: "#2B2466",
    secondary: "#5C328F",
    secondaryDark: "#733EB3",
    secondaryDarker: "#9B50E0",
    dark: "#b4a5de",
    black: "#000",
    light: "#EEE",
    lightColored: "#C8C5DB",
    lightColoredDarker: "#A8A5B8",
    red: "#ff6961",
    redDark: "#B34944",
    green: "#8DEB7F",
    greenDark: "#5F9E55",
    background: "#443f48",
    backgroundLight: "#625a67",
    backgroundFont: "#EEE",
    cameraDark: "#333",
    cameraDarker: "#111",
    cameraLight: "#eee",
  },
  fonts: ["sans-serif", "Montserrat"],
  fontSizes: {
    small: "1em",
    medium: "2em",
    large: "3em",
  },
} as const;
