export const lightTheme = {
  colors: {
    background: "#9B50E0",
    backgroundDark: "#733EB3",
    backgroundDarker: "#5C328F",
    background2: "#4C3EB3",
    background2Light: "#E7E4FE",
    background2Dark: "#2B2466",
    background2Hover: "#2B2466",
    dark: "#2b2927",
    black: "#000",
    middle: "#ACC18A",
    darkMiddle: "#81926a",
    foreground2: "#DAFEB7",
    foreground: "#F2FBE0",
    light: "#EEE",
    lightColored: "#E7E4FE",
    lightColoredDarker: "#CECAFE",
    red: "#ff6961",
    white: "#FFF",
  },
  fonts: ["sans-serif", "Roboto"],
  fontSizes: {
    small: "1em",
    medium: "2em",
    large: "3em",
  },
} as const;
