export const lightTheme = {
  colors: {
    primary: "#4C3EB3",
    primaryLight: "#E7E4FE",
    primaryDark: "#2B2466",
    primaryHover: "#2B2466",
    secondary: "#9B50E0",
    secondaryDark: "#733EB3",
    secondaryDarker: "#5C328F",
    dark: "#2b2927",
    black: "#000",
    light: "#EEE",
    lightColored: "#E7E4FE",
    lightColoredDarker: "#CECAFE",
    red: "#ff6961",
    redDark: "#B34944",
    green: "#8DEB7F",
    greenDark: "#5F9E55",
    background: "#FFF",
    backgroundLight: "#E7E4FE",
    backgroundFont: "#2b2927",
  },
  fonts: ["sans-serif", "Roboto"],
  fontSizes: {
    small: "1em",
    medium: "2em",
    large: "3em",
  },
} as const;
