export const defaultTheme = {
  colors: {
    background: "#BB86FC",
    backgroundDark: "#9039fa",
    backgroundDarker: "#7b13f9",
    background2: "#6200EE",
    background2Light: "#f5eeff",
    background2Dark: "#4a00b3",
    dark: "#2b2927",
    black: "#000",
    middle: "#ACC18A",
    darkMiddle: "#81926a",
    foreground2: "#DAFEB7",
    foreground: "#F2FBE0",
    light: "#EEE",
    red: "#ff6961",
    white: "#FFF",
  },
  fonts: ["sans-serif", "Roboto"],
  fontSizes: {
    small: "1em",
    medium: "2em",
    large: "3em",
  },
} as const;
